name: Integration

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  integrate-revision:
    if: github.ref == 'refs/heads/main'
    name: Integrate revision
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.IDENTUS_CI }}
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "sdk-ts", "release": false, "version": "${{ github.sha }}" }'

  integrate-release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Integrate release
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Get tag
        id: tag
        run: echo "name=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.IDENTUS_CI }}
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "sdk-ts", "release": true, "version": "${{ steps.tag.outputs.name }}" }'
