name: Release wallet-sdk-ts

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for npm trusted publishing (OIDC)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive
          token: ${{ secrets.IDENTUS_CI }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      # Ensure npm version >= 11.5.1 (lowest supporting trusted publishing)
      - name: Upgrade npm
        run: npm install -g npm@^11.5.1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: nightly
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: crazy-max/ghaction-import-gpg@d6f3f49f3345e29369fe57596a3ca8f94c4d2ca7 # v5.4.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          passphrase:  ${{ secrets.HYP_BOT_GPG_PASSWORD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: false
      - name: Release
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
        run: |
          echo "Using npm version: $(npm -v)"
          npm ci 
          npm audit signatures
          npx semantic-release
